# Generated by Django 2.1.2 on 2018-12-27 22:31

import avatar.utils
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_labsresearch_upcoming'),
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('png', models.ImageField(blank=True, help_text='The custom avatar PNG.', null=True, upload_to=avatar.utils.get_upload_filename)),
                ('svg', models.FileField(blank=True, help_text='The custom avatar SVG.', null=True, upload_to=avatar.utils.get_upload_filename)),
                ('profile', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Profile')),
            ],
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='custom_avatar_png',
        ),
        migrations.RemoveField(
            model_name='avatar',
            name='svg',
        ),
        migrations.AddField(
            model_name='avatar',
            name='custom_avatar',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='avatar.CustomAvatar'),
        ),
    ]
