# Generated by Django 2.1.2 on 2019-01-09 00:18

import avatar.utils
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import economy.models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_bounty_estimated_hours'),
        ('avatar', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseAvatar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(db_index=True, default=economy.models.get_time)),
                ('modified_on', models.DateTimeField(default=economy.models.get_time)),
                ('active', models.BooleanField(default=False)),
                ('svg', models.FileField(blank=True, help_text='The avatar SVG.', null=True, upload_to=avatar.utils.get_upload_filename)),
                ('png', models.ImageField(blank=True, help_text='The avatar PNG.', null=True, upload_to=avatar.utils.get_upload_filename)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomAvatar',
            fields=[
                ('baseavatar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='avatar.BaseAvatar')),
                ('recommended_by_staff', models.BooleanField(default=False)),
                ('config', django.contrib.postgres.fields.jsonb.JSONField(default=dict, help_text='The JSON configuration.')),
            ],
            options={
                'abstract': False,
            },
            bases=('avatar.baseavatar',),
        ),
        migrations.CreateModel(
            name='SocialAvatar',
            fields=[
                ('baseavatar_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='avatar.BaseAvatar')),
                ('source', models.CharField(db_index=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('avatar.baseavatar',),
        ),
        migrations.AddField(
            model_name='baseavatar',
            name='profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='avatar_baseavatar_related', to='dashboard.Profile'),
        ),
    ]
